# Generated by Django 4.2.3 on 2023-09-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smashapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
