# Generated by Django 4.2.3 on 2023-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smashapp", "0007_auto_20230924_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
