# Generated by Django 4.2.3 on 2023-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smashapp", "0008_alter_picture_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
