# Generated by Django 4.2.3 on 2023-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smashapp", "0011_picture_processed_image_alter_picture_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
