# Generated by Django 4.2.3 on 2023-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smashapp", "0012_picture_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
    ]
